import time
import json
import os
import sys
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from logic import calculate_match_score, extract_features
from models_loader import model_manager

sys.stdout.reconfigure(encoding='utf-8')

# Paths generated by AntiGravity
WALLET_Q = r"C:\Users\GIMINDU\.gemini\antigravity\brain\813b7b47-39cb-46d3-adda-3e24de270f82\wallet_q_1773943867242.png"
WALLET_T = r"C:\Users\GIMINDU\.gemini\antigravity\brain\813b7b47-39cb-46d3-adda-3e24de270f82\wallet_t_1773943883754.png"
BACKPACK_Q = r"C:\Users\GIMINDU\.gemini\antigravity\brain\813b7b47-39cb-46d3-adda-3e24de270f82\backpack_q_1773943901389.png"
BACKPACK_T = r"C:\Users\GIMINDU\.gemini\antigravity\brain\813b7b47-39cb-46d3-adda-3e24de270f82\backpack_t_1773943922022.png"

def run_evaluation():
    print("Loading Full Multimodal AI Models...")
    model_manager.load_models()
    
    # ---------------------------------------------------------
    # MULTIMODAL GROUND TRUTH DATASET
    # ---------------------------------------------------------
    test_pairs = [
        # TRUE MATCHES
        {
            "q": {"name": "Black Leather Wallet", "description": "Lost near central park.", "category": "documents", "subcategory": "wallet", "color": "black", "location": "central park", "date_lost": "2026-03-01"},
            "t": {"name": "Found black wallet", "description": "Found a black gents wallet.", "category": "documents", "subcategory": "wallet", "color": "black", "location": "central park", "date_found": "2026-03-01"},
            "q_img": WALLET_Q, "t_img": WALLET_T, "label": 1
        },
        {
            "q": {"name": "Blue Nike Backpack", "description": "Dark blue sports bag", "category": "personal items", "subcategory": "bag", "color": "blue", "location": "train station", "date_lost": "2026-03-15"},
            "t": {"name": "Blue bag", "description": "Blue rucksack", "category": "personal items", "subcategory": "bag", "color": "blue", "location": "train station", "date_found": "2026-03-16"},
            "q_img": BACKPACK_Q, "t_img": BACKPACK_T, "label": 1
        },
        # TRUE NEGATIVES
        {
            "q": {"name": "Black Leather Wallet", "description": "Lost near central park.", "category": "documents", "subcategory": "wallet", "color": "black", "location": "central park", "date_lost": "2026-03-01"},
            "t": {"name": "Blue bag", "description": "Blue rucksack", "category": "personal items", "subcategory": "bag", "color": "blue", "location": "train station", "date_found": "2026-03-16"},
            "q_img": WALLET_Q, "t_img": BACKPACK_T, "label": 0
        },
        {
            "q": {"name": "Blue Nike Backpack", "description": "Dark blue sports bag", "category": "personal items", "subcategory": "bag", "color": "blue", "location": "train station", "date_lost": "2026-03-15"},
            "t": {"name": "Found black wallet", "description": "Found a black gents wallet.", "category": "documents", "subcategory": "wallet", "color": "black", "location": "central park", "date_found": "2026-03-01"},
            "q_img": BACKPACK_Q, "t_img": WALLET_T, "label": 0
        }
    ]
    
    expanded_dataset = []
    for _ in range(3): # Total 12 inference pairs to test MobileNet speed
        expanded_dataset.extend(test_pairs)
    
    y_true = []
    y_pred = []
    inference_times = []

    print(f"Starting Multimodal Inference on {len(expanded_dataset)} images...")

    for pair in expanded_dataset:
        query_item = pair["q"]
        target_item = pair["t"]
        q_img = pair["q_img"]
        t_img = pair["t_img"]
        y_true.append(pair["label"])
        
        start_time = time.time()
        
        # EXTRACT MULTIMODAL FEATURES
        q_feats = extract_features(query_item, img_path=q_img)
        t_feats = extract_features(target_item, img_path=t_img)
        
        # SCORE (Threshold = 0.4)
        score = calculate_match_score(query_item, q_img, q_feats, target_item, t_img, t_feats)
        
        inference_times.append(time.time() - start_time)
        prediction = 1 if score > 0.4 else 0
        y_pred.append(prediction)
        
    acc = accuracy_score(y_true, y_pred) * 100
    prec = precision_score(y_true, y_pred, zero_division=0) * 100
    rec = recall_score(y_true, y_pred, zero_division=0) * 100
    f1 = f1_score(y_true, y_pred, zero_division=0) * 100
    avg_inference = sum(inference_times) / len(inference_times)
    
    results = {
        "Accuracy_Hybrid": acc,
        "Precision_Hybrid": prec,
        "Recall_Hybrid": rec,
        "F1_Hybrid": f1,
        "Avg_Inference_Sec": avg_inference
    }
    
    with open("results_hybrid.json", "w") as f:
        json.dump(results, f, indent=4)
        
    print("Inference Complete. Results saved.")
        
if __name__ == "__main__":
    run_evaluation()
