import time
import json
import os
import sys
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from logic import calculate_match_score, extract_features
from models_loader import model_manager

sys.stdout.reconfigure(encoding='utf-8')

# Paths generated by AntiGravity
WALLET_Q = r"C:\Users\GIMINDU\.gemini\antigravity\brain\813b7b47-39cb-46d3-adda-3e24de270f82\wallet_q_1773943867242.png"
WALLET_T = r"C:\Users\GIMINDU\.gemini\antigravity\brain\813b7b47-39cb-46d3-adda-3e24de270f82\wallet_t_1773943883754.png"
BACKPACK_Q = r"C:\Users\GIMINDU\.gemini\antigravity\brain\813b7b47-39cb-46d3-adda-3e24de270f82\backpack_q_1773943901389.png"
BACKPACK_T = r"C:\Users\GIMINDU\.gemini\antigravity\brain\813b7b47-39cb-46d3-adda-3e24de270f82\backpack_t_1773943922022.png"
ID_Q = r"C:\Users\GIMINDU\.gemini\antigravity\brain\813b7b47-39cb-46d3-adda-3e24de270f82\id_q_1773946081235.png"
ID_T = r"C:\Users\GIMINDU\.gemini\antigravity\brain\813b7b47-39cb-46d3-adda-3e24de270f82\id_t_1773946097079.png"


def run_evaluation():
    print("Loading Full Multimodal AI Models (including EasyOCR)...")
    model_manager.load_models()
    
    # ---------------------------------------------------------
    # MULTIMODAL GROUND TRUTH DATASET
    # ---------------------------------------------------------
    base_pairs = [
        # TRUE MATCHES
        {
            "q": {"name": "Black Leather Wallet", "description": "Lost near park", "category": "personal items", "subcategory": "wallet", "color": "black", "location": "central park", "date_lost": "2026-03-01"},
            "t": {"name": "Found black wallet", "description": "Found a gents wallet.", "category": "personal items", "subcategory": "wallet", "color": "black", "location": "central park", "date_found": "2026-03-01"},
            "q_img": WALLET_Q, "t_img": WALLET_T, "label": 1
        },
        {
            "q": {"name": "Blue Nike Backpack", "description": "sports bag", "category": "personal items", "subcategory": "bag", "color": "blue", "location": "train station", "date_lost": "2026-03-15"},
            "t": {"name": "Blue bag", "description": "rucksack", "category": "personal items", "subcategory": "bag", "color": "blue", "location": "train station", "date_found": "2026-03-16"},
            "q_img": BACKPACK_Q, "t_img": BACKPACK_T, "label": 1
        },
        { # OCR MATCH
            "q": {"name": "JOHN DOE", "description": "student ID card", "category": "documents", "subcategory": "id", "color": "white", "location": "campus", "date_lost": "2026-03-19"},
            "t": {"name": "JOHN DOE", "description": "found student ID", "category": "documents", "subcategory": "id", "color": "white", "location": "campus", "date_found": "2026-03-19"},
            "q_img": ID_Q, "t_img": ID_T, "label": 1
        },
        # TRUE NEGATIVES
        {
            "q": {"name": "Black Leather Wallet", "description": "Lost near park", "category": "personal items", "subcategory": "wallet", "color": "black", "location": "central park", "date_lost": "2026-03-01"},
            "t": {"name": "Blue bag", "description": "rucksack", "category": "personal items", "subcategory": "bag", "color": "blue", "location": "train station", "date_found": "2026-03-16"},
            "q_img": WALLET_Q, "t_img": BACKPACK_T, "label": 0
        },
        {
            "q": {"name": "Blue Nike Backpack", "description": "sports bag", "category": "personal items", "subcategory": "bag", "color": "blue", "location": "train station", "date_lost": "2026-03-15"},
            "t": {"name": "Found black wallet", "description": "Found a gents wallet.", "category": "personal items", "subcategory": "wallet", "color": "black", "location": "central park", "date_found": "2026-03-01"},
            "q_img": BACKPACK_Q, "t_img": WALLET_T, "label": 0
        },
        {
            "q": {"name": "JOHN DOE", "description": "student ID card", "category": "documents", "subcategory": "id", "color": "white", "location": "campus", "date_lost": "2026-03-19"},
            "t": {"name": "Found black wallet", "description": "Found a gents wallet.", "category": "personal items", "subcategory": "wallet", "color": "black", "location": "central park", "date_found": "2026-03-01"},
            "q_img": ID_Q, "t_img": WALLET_T, "label": 0
        }
    ]
    
    # Expand to 12 pairs to test latency and stabilize percentages
    test_pairs = []
    for _ in range(2):
        test_pairs.extend(base_pairs)
        
    def evaluate_set(dataset, vision_only=False):
        y_true = []
        y_pred = []
        
        for pair in dataset:
            q = dict(pair["q"])
            t = dict(pair["t"])
            
            if vision_only:
                # Blank out all text and meta fields to force the algorithm to rely ONLY on CLIP/MobileNet Image embeddings
                for k in q: q[k] = ""
                for k in t: t[k] = ""
                
            q_img = pair["q_img"]
            t_img = pair["t_img"]
            
            y_true.append(pair["label"])
            
            q_feats = extract_features(q, img_path=q_img)
            t_feats = extract_features(t, img_path=t_img)
            
            score = calculate_match_score(q, q_img, q_feats, t, t_img, t_feats)
            y_pred.append(1 if score > 0.4 else 0)
            
        acc = accuracy_score(y_true, y_pred) * 100
        prec = precision_score(y_true, y_pred, zero_division=0) * 100
        rec = recall_score(y_true, y_pred, zero_division=0) * 100
        f1 = f1_score(y_true, y_pred, zero_division=0) * 100
        return acc, prec, rec, f1

    # RUN EXP 2 (Vision Only)
    print("Running Experiment 2 (Vision Only)...")
    acc_v, prec_v, rec_v, f1_v = evaluate_set(test_pairs, vision_only=True)
    
    # RUN EXP 4 (Hybrid + OCR)
    print("Running Experiment 4 (Hybrid + OCR)...")
    acc_o, prec_o, rec_o, f1_o = evaluate_set(test_pairs, vision_only=False)

    results = {
        "Exp2": {"Acc": acc_v, "Prec": prec_v, "Rec": rec_v, "F1": f1_v},
        "Exp4": {"Acc": acc_o, "Prec": prec_o, "Rec": rec_o, "F1": f1_o}
    }
    
    with open("results_exp2_exp4.json", "w") as f:
        json.dump(results, f, indent=4)
        
    print("Inference Complete. Results saved.")
        
if __name__ == "__main__":
    run_evaluation()
